services:
  - type: web
    name: youtube-screen-streamer
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
    # Note: Render's web services don't support screen capture
    # Consider using a background worker instead 